apiVersion: v1
kind: Service
metadata:
  name: note-api-service
  namespace: note-app
spec:
  selector:
    app: note-api
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30080